version: '2'
services:

  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      php_example:
        aliases:
          - nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./datadog-config.json:/etc/datadog-config.json
    expose:
      - "8080"
    ports:
      - "8080:8080"

  dd-agent:
    image: 'datadog/agent'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - '/proc/:/host/proc/:ro'
      - '/sys/fs/cgroup/:/host/sys/fs/cgroup:ro'
    environment:
      - 'DD_API_KEY=YOUR_KEY_HERE'
      - 'DD_APM_ENABLED=true'
      - 'DD_LOG_LEVEL=ERROR'
    networks:
      php_example:
        aliases:
          - dd-agent
    expose:
      - "8126"
    ports:
      - "8126:8126"

  php_fpm:
    image: php:7-fpm
    networks:
      php_example:
        aliases:
          - php_fpm
    volumes:
      - ./php-fpm.conf:/usr/local/etc/php-fpm.d/php-fpm.conf
      - ./index.php:/var/www/index.php
      - ./error.php:/var/www/error.php
    expose:
      - "9000"
    ports:
      - "9000:9000"

networks:
  php_example: {}
